### ISSUE TITLE
password value still viewable in page source!

### ISSUE THREAD

**Issue by wvandenbossche** [BeverCRM/PCF-PasswordField#8]
Hi,

Good effort! thank you. But main concern is that the real password value is still traceable in page source when not clicked on the 'eye' icon.

Also, this control cannot be used when this field is added to a 'Quick view form'

Regard
Wim

**Comment by Hovhannes-Dilanyan** [comment]
Hello,

Thank you for your feedback. I'm pleased to inform you that the issue has been fixed in the latest version ([v1.1.0](https://github.com/BeverCRM/PCF-PasswordField/releases/tag/v1.1.0)).

**Comment by Hovhannes-Dilanyan** [comment]
Hello,

Thank you for your feedback. I'm pleased to inform you that the issue has been fixed in the latest version ([v1.1.0](https://github.com/BeverCRM/PCF-PasswordField/releases/tag/v1.1.0)).
You can download it from the following link. https://marketplace.bevercrm.com/pcf-controls/PasswordField

We appreciate your help in bringing this to our attention.
Please let us know if you encounter any other issues or have any further questions or concerns.

Best Regards,
Hovhannes
Bever

**Comment by Hovhannes-Dilanyan** [comment]
As for the **Quick View Form,** this is actually a limitation of Dynamics 365, you can't add a control to this form.
